spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/job_postings
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
admin:
  username: admin
  password: password
jwt:
  key: key